version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  build:
    commands:
      - echo "Zipping Flask app..."
      - zip -r app.zip python-hello-world/
artifacts:
  files:
    - app.zip
